---
- name: Install yum-cron.
  become: yes
  yum:
    name: yum-cron
    state: present

- name: Copy the configuration file (CentOS 6).
  become: yes
  template:
    src: etc/sysconfig/yum-cron.j2
    dest: /etc/sysconfig/yum-cron
  notify:
    - restart yum-cron
  when: ansible_distribution_major_version == "6"

- name: Copy the configuration file (CentOS 7).
  become: yes
  template:
    src: etc/yum/yum-cron.conf.j2
    dest: /etc/yum/yum-cron.conf
  notify:
    - restart yum-cron
  when: ansible_distribution_major_version == "7"

- name: Start yum-cron.
  become: yes
  service:
    name: yum-cron
    state: started
    enabled: yes
